name: Deploy multi-docker
on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t pkarczmarczyk/react-test -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true pkarczmarczyk/react-test npm test

            - run: docker build -t pkarczmarczyk/docker-complex-client ./client
            - run: docker build -t pkarczmarczyk/docker-complex-nginx ./nginx
            - run: docker build -t pkarczmarczyk/docker-complex-server ./server
            - run: docker build -t pkarczmarczyk/docker-complex-worker ./worker

            - run: docker push pkarczmarczyk/docker-complex-client
            - run: docker push pkarczmarczyk/docker-complex-nginx
            - run: docker push pkarczmarczyk/docker-complex-server
            - run: docker push pkarczmarczyk/docker-complex-worker
